---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: quoteattestation
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./test-yamls
  prune: true
  sourceRef:
    kind: GitRepository
    name: quoteattestation
  targetNamespace: default

