---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: quoteattestation
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/Ruoyu-y/test-resource-dep

