apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: "8188404215066801364"
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/Ruoyu-y/test-flux
status: {}
