apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust7854380244462262194
  namespace: default
spec:
  interval: 5m0s
  path: clusters/akraino_scc_overlay1+edge-1/context/7854380244462262194
  prune: true
  sourceRef:
    kind: GitRepository
    name: "7854380244462262194"
  targetNamespace: default
status: {}
