apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust1603482446489920241
  namespace: default
spec:
  interval: 5m0s
  path: clusters/akraino_scc_overlay1+edge-1/context/1603482446489920241
  prune: true
  sourceRef:
    kind: GitRepository
    name: "1603482446489920241"
  targetNamespace: default
status: {}
